
name: nexus

on:
  workflow_call:
    inputs:
      distribution:
        required: false
        type: string
        default: temurin
      java-version:
        required: false
        type: string
      artifact-path:
        required: false
        type: string
        default: |
          **/target/*.jar
      nexus-id:
        required: false
        type: string
      nexus-central:
        required: false
        type: string
        default: https://repo1.maven.org/maven2/
      env-file:
        required: false
        type: string
        default: .env
    secrets:
      NEXUS_USERNAME:
        required: true
      NEXUS_PASSWORD:
        required: true
      NEXUS_SNAPSHOT_URL:
        required: true
      NEXUS_RELEASE_URL:
        required: true

jobs:
  nexus:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: import-env
        if: ${{ hashFiles(inputs.env-file) != '' }}
        run: |
          cat ${{inputs.env-file}}
          cat ${{inputs.env-file}} >> $GITHUB_ENV

      - name: load-java-version
        run: |
          JAVA_VERSION=${{ inputs.java-version }}

          if [ -z "${JAVA_VERSION}" ]; then
            JAVA_VERSION=${{ env.JAVA_VERSION }}
          fi
          if [ -z "${JAVA_VERSION}" ]; then
            JAVA_VERSION=$(grep '<java.version>' pom.xml | sed -n 's/.*<java.version>\(.*\)<\/java.version>.*/\1/p')
          fi
          if [ -z "${JAVA_VERSION}" ]; then
            JAVA_VERSION=21
          fi
          
          echo "JAVA_VERSION=${JAVA_VERSION}"
          echo "JAVA_VERSION=${JAVA_VERSION}" >> $GITHUB_ENV

      - name: setup-java
        uses: actions/setup-java@v4
        if: ${{ env.JAVA_VERSION != '' }}
        with:
          distribution: ${{ inputs.distribution }}
          java-version: ${{ env.JAVA_VERSION }}
      - name: load-nexus-id
        run: |
          NEXUS_ID=${{ inputs.nexus-id }}
          if [ -z "${NEXUS_ID}" ]; then
            NEXUS_ID=$(echo "${{ github.repository }}" | cut -d '/' -f 1)
          fi
          echo "NEXUS_ID=${NEXUS_ID}"
          echo "NEXUS_ID=${NEXUS_ID}" >> $GITHUB_ENV

      - name: init-maven
        run: curl -sL https://github.com/cc332030/maven/raw/master/script/linux/init-maven.sh | sh
        env:
          NEXUS_ID: ${{ env.NEXUS_ID }}
          MAVEN_CENTRAL: ${{ inputs.nexus-central }}
          NEXUS_USERNAME: ${{ secrets.NEXUS_USERNAME }}
          NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
          NEXUS_SNAPSHOT_URL: ${{ secrets.NEXUS_SNAPSHOT_URL }}
          NEXUS_RELEASE_URL: ${{ secrets.NEXUS_RELEASE_URL }}
#      - name: verify
#        run: sh mvnw help:effective-settings
      - name: cache
        uses: actions/cache@v4
        with:
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          path: |
            ~/.m2/repository/
            ~/.m2/wrapper/
      - name: deploy
        run: |
          CORE_NUM=$(grep -c ^processor /proc/cpuinfo)
          echo "CORE_NUM=${CORE_NUM}"

          sh mvnw -T ${CORE_NUM}C clean deploy -U

        env:
          NEXUS_ID: ${{ env.NEXUS_ID }}
          NEXUS_SNAPSHOT_URL: ${{ secrets.NEXUS_SNAPSHOT_URL }}
          NEXUS_RELEASE_URL: ${{ secrets.NEXUS_RELEASE_URL }}
      - name: init-maven-clean
        if: ${{ always() }}
        run: curl -sL https://github.com/cc332030/maven/raw/master/script/linux/init-maven-clean.sh | sh
      - id: artifact-name
        name: artifact-name
        run: |
          echo "artifact-name=${{ github.event.repository.name }}.${{ github.ref_name }}.${{ github.run_id }}" >> $GITHUB_OUTPUT
      - name: upload-artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.artifact-name.outputs.artifact-name }}
          path: ${{ inputs.artifact-path }}
          retention-days: 7
